import React, { useEffect, useRef, useState } from 'react';
import { articles, articleFor, caseService, currentInteraction, handoffFor, isResponsible, playerFor, players, rgSteps, routingFor } from './domain';
import type { Article, CaseId, CaseRecord, View } from './domain';

const paths:Record<string,string>={Inbox:'M4 4h16v16H4z M4 13h5l2 3h2l2-3h5',Cases:'M4 6h7l2 2h7v12H4z M4 6V4h7l2 2',Players:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M19 8v6 M16 11h6',Knowledge:'M12 6C8 3 4 4 3 5v14c3-2 6-1 9 1 3-2 6-3 9-1V5c-3-2-6-1-9 1v14',Supervisor:'M4 20V10h3v10 M10 20V4h3v16 M16 20v-8h3v8',arrow:'M5 12h14 M13 6l6 6-6 6',chat:'M4 4h16v12H9l-5 4z',mail:'M3 5h18v14H3z M3 5l9 7 9-7',shield:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z M8 12l3 3 5-6',search:'M10 17a7 7 0 1 0 0-14 7 7 0 0 0 0 14 M15 15l6 6',spark:'M12 3l2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z',clock:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20 M12 6v6l4 2',check:'M5 12l4 4L19 6',close:'M6 6l12 12 M6 18L18 6',reset:'M4 9a8 8 0 1 1 0 7 M4 3v6h6',architecture:'M9 2h6v5H9z M3 17h6v5H3z M15 17h6v5h-6z M12 7v5 M6 17v-5h12v5'};
export function Icon({name,size=19}:{name:string;size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.chat}/></svg>;}
function useStore(){const [s,set]=useState(caseService.getSnapshot());useEffect(()=>caseService.subscribe(()=>set(caseService.getSnapshot())),[]);return s;}
function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>;}
function Label({children}:{children:React.ReactNode}){return <span className="eyebrow">{children}</span>;}
function Avatar({c,small=false}:{c:CaseRecord;small?:boolean}){return <span className={`avatar ${small?'small':''} ${isResponsible(c)?'sage':''}`}>{playerFor(c).initials}</span>;}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const prev=document.activeElement as HTMLElement;const el=ref.current;el?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'&&el){const all=Array.from(el.querySelectorAll<HTMLElement>('button,input,select,textarea,a[href],[tabindex="0"]'));const first=all[0],last=all[all.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===el)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prev?.focus();};},[onClose]);
 return <div className="modal-shade" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref}><header><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Fechar"><Icon name="close"/></button></header>{children}</div></div>;
}
function PlayerPanel({c,onCase}:{c:CaseRecord;onCase?:()=>void}){const p=playerFor(c);return <>
 <div className="profile-intro"><Avatar c={c}/><div><h2>{p.name}</h2><span className="muted">{p.id}</span></div></div>
 <Badge tone={isResponsible(c)?'green':'amber'}>{p.account}</Badge>
 <dl className="facts"><div><dt>Idioma</dt><dd>{p.language}</dd></div><div><dt>Cliente desde</dt><dd>{p.since}</dd></div><div><dt>Preferências</dt><dd>{p.preferences}</dd></div>{p.payment&&<div><dt>Evento de pagamento</dt><dd>{p.payment}</dd></div>}</dl>
 <section className="memory"><Label>Contexto anterior</Label>{p.memory.map(m=><p key={m}><Icon name="clock" size={15}/>{m}</p>)}</section>
 <section className="panel-section"><Label>Case relacionado</Label><button className="case-link" onClick={onCase}><span><strong>{c.id}</strong><small>{c.title}</small></span><Icon name="arrow"/></button><Badge>{c.status}</Badge></section>
 <p className="boundary"><Icon name="shield" size={15}/> Somente contexto operacional. Dados sensíveis permanecem nos sistemas de origem.</p>
 </>;}
function KnowledgeCard({article,onSource,onUse,compact=false}:{article:Article;onSource:()=>void;onUse?:()=>void;compact?:boolean}){return <article className={`knowledge-card ${compact?'compact':''}`}><div className="row spread"><Badge tone="green">Aprovado · Demo</Badge><span className="muted">v{article.version}</span></div><h3>{article.title}</h3><p className="muted">{article.category} · {article.updated}</p><ol>{article.guidance.map(g=><li key={g}>{g}</li>)}</ol><p className="source-ref">{article.source}</p><div className="row"><button className="text-button" onClick={onSource}>Ver fonte <Icon name="arrow" size={15}/></button>{onUse&&<button className="secondary" onClick={onUse}>Usar orientação</button>}</div></article>;}
function CasePanel({c,full=false,onHandoff}:{c:CaseRecord;full?:boolean;onHandoff:()=>void}){
 const [note,setNote]=useState('');const rg=isResponsible(c);const done=c.status==='Resolvido';
 return <><div className="row spread"><Label>Case Center</Label><Badge tone={done?'green':'amber'}>{c.status}</Badge></div><h2 className="case-id">{c.id}</h2><h3>{c.title}</h3><dl className="facts"><div><dt>Prioridade</dt><dd>{c.priority}</dd></div><div><dt>Fila</dt><dd>{c.queue}</dd></div><div><dt>Responsável</dt><dd>{c.owner}</dd></div><div><dt>SLA</dt><dd>{c.sla} min <span className="muted">· referência da demo</span></dd></div><div><dt>Motivo</dt><dd>{c.reason}</dd></div></dl>
 <div className="tags">{c.tags.map(t=><span key={t}>#{t}</span>)}</div>
 {rg&&<section className="policy-checklist"><Label>Checklist obrigatório</Label>{rgSteps.map(step=><label key={step}><input type="checkbox" checked={c.checklist.includes(step)} disabled={done} onChange={()=>caseService.dispatch({type:'check',id:c.id,step})}/>{step}</label>)}<p className="muted">Nenhum bloqueio ou autoexclusão real é realizado.</p></section>}
 <div className="case-actions">{!rg&&<button className="primary" disabled={done||c.status==='Validação solicitada'} onClick={()=>caseService.dispatch({type:'validate',id:c.id})}>Solicitar validação</button>}<button className="secondary" disabled={done||c.owner==='Rafael Lima'} onClick={onHandoff}>{rg?'Encaminhar ao especialista':'Transferir'}</button><button className="secondary" disabled={done||c.status==='Aguardando cliente'} onClick={()=>caseService.dispatch({type:'wait',id:c.id})}>Aguardar cliente</button><button className="secondary" disabled={done} onClick={()=>caseService.dispatch({type:'resolve',id:c.id})}>Resolver caso</button></div>
 <section className="panel-section"><Label>Notas internas · {c.notes.length}</Label>{c.notes.map((n,i)=><p className="note" key={i}>{n}</p>)}<label className="sr-only" htmlFor={`note-${c.id}`}>Adicionar nota interna</label><textarea id={`note-${c.id}`} placeholder="Adicionar nota interna ao Case…" value={note} onChange={e=>setNote(e.target.value)} maxLength={1500}/><button className="text-button" disabled={!note.trim()} onClick={()=>{caseService.dispatch({type:'note',id:c.id,text:note});setNote('');}}>Adicionar nota <Icon name="arrow" size={15}/></button></section>
 <section className="panel-section"><Label>Interações relacionadas</Label>{c.interactions.map(i=><div className="linked-interaction" key={i.id}><Icon name={i.channel==='Email'?'mail':'chat'}/><div><strong>{i.channel} #{i.id}</strong><small>{i.ended?'Encerrada':'Em andamento'}</small>{full&&<p>{i.summary}</p>}</div></div>)}<p className="muted">A interação pode terminar. O Case continua.</p></section>
 <section className="panel-section"><Label>Case timeline</Label><ol className="timeline">{c.timeline.map((e,i)=><li key={i}><time>{e.time}</time><span>{e.text}</span></li>)}</ol></section>
 {full&&<><section className="panel-section"><Label>Conhecimento consultado</Label>{c.knowledge.length?c.knowledge.map(k=><p key={k}>{articles.find(a=>a.id===k)?.title}</p>):<p className="muted">Nenhuma consulta registrada ainda.</p>}</section><section className="panel-section"><Label>Desfecho</Label><p>{c.outcome}</p>{c.handoffSummary&&<><Label>Resumo de handoff preservado</Label><p>{c.handoffSummary}</p></>}</section></>}
 </>;
}
function AssistPanel({c,onSource,onKnowledge}:{c:CaseRecord;onSource:(a:Article)=>void;onKnowledge:()=>void}){const r=routingFor(c),a=articleFor(c);return <>
 <div className="assist-heading"><Icon name="spark"/><Label>Assist · contexto conectado</Label></div><h2>O que está acontecendo</h2><p className="lead-small">{currentInteraction(c).summary}</p><dl className="facts"><div><dt>Intenção</dt><dd>{r.intent}</dd></div><div><dt>Sentimento</dt><dd>{r.sentiment}</dd></div><div><dt>Tópico</dt><dd>{r.secondary}</dd></div><div><dt>Sinal de política</dt><dd>{r.policy}</dd></div><div><dt>Sinal operacional</dt><dd>{isResponsible(c)?'Encaminhamento prioritário':'Validação pendente'}</dd></div></dl><section className="memory"><Label>Contexto anterior</Label><p>{playerFor(c).memory[0]}</p></section><section className="panel-section"><Label>Política relevante</Label><button className="article-link" onClick={onKnowledge}>{a.title}<Icon name="arrow" size={15}/></button></section><section className="suggestion"><Label>Resposta sugerida</Label><p>{a.response}</p><button className="text-button" onClick={()=>onSource(a)}>Fonte: {a.id} · v{a.version}</button><button className="primary" disabled={currentInteraction(c).ended} onClick={()=>{caseService.dispatch({type:'knowledge',id:c.id,articleId:a.id});caseService.dispatch({type:'draft',id:c.id,text:a.response});}}>Usar resposta</button></section><section className="panel-section"><Label>Próxima melhor ação</Label><p>{isResponsible(c)?'Acolher o pedido e seguir o checklist de encaminhamento especializado.':'Solicitar validação e transferir o contexto para Verification.'}</p></section>
 </>;}
function Architecture(){return <div className="architecture"><p className="lead-small">Um único workspace para a conversa, o caso, o contexto do jogador, conhecimento e inteligência.</p><div className="arch-channels">{['Voice','WhatsApp','WebChat','Email'].map(x=><span key={x}>{x}</span>)}</div><div className="arch-line">↓</div><div className="arch-flex"><Label>Twilio Flex</Label><h3>Agent Workspace · TaskRouter · Supervisor · Flex Plugins</h3><p>Workspace do agente e orquestração de trabalho. Plugins compõem a experiência BetMGM; TaskRouter decide o encaminhamento.</p></div><div className="arch-line">↙ <span>camadas conectadas</span> ↘</div><div className="arch-columns"><section><Label>BetMGM business layer</Label><h3>Case Center · Player 360</h3><p><b>Case Service</b> — trabalho persistente independente da interação.</p><p><b>BetMGM Systems</b> — sistemas de registro para dados sensíveis de negócio.</p></section><section><Label>Twilio conversation layer</Label><p><b>Conversation Orchestrator</b> — orquestração contínua de conversas.</p><p><b>Conversation Memory</b> — contexto conversacional histórico seguro.</p><p><b>Enterprise Knowledge</b> — políticas e procedimentos aprovados.</p><p><b>Conversation Intelligence</b> — entendimento e sinais operacionais.</p></section></div><p className="boundary">Arquitetura alvo. Nesta demonstração, Cases, canais, conhecimento, memória e inteligência usam dados locais sintéticos.</p></div>;}
export type HostMode = 'FLEX_HOST' | 'STANDALONE_HOST';
export function Workspace({host='STANDALONE_HOST',view:externalView,onNavigate}:{host?:HostMode;view?:View;onNavigate?:(v:View)=>void}){
 const embedded=host==='FLEX_HOST';
 const state=useStore();const [localView,setView]=useState<View>('Inbox');const view=externalView||localView;const c=state.cases[state.selected];
 const [tab,setTab]=useState('Player');const [modal,setModal]=useState<'architecture'|'demo'|'handoff'|'email'|'reset'|'source'|'signal'|null>(null);const [source,setSource]=useState<Article>(articles[0]);
 const [signal,setSignal]=useState(0);const [search,setSearch]=useState('');const [filters,setFilters]=useState({status:'',priority:'',queue:'',owner:''});const [category,setCategory]=useState('');const [caseOpen,setCaseOpen]=useState(false);
 const navigate=(v:View)=>{setSearch('');if(onNavigate)onNavigate(v);else setView(v);};
 const select=(id:CaseId)=>{caseService.dispatch({type:'select',id});setTab('Player');};
 const openSource=(a:Article)=>{setSource(a);if(view==='Inbox')caseService.dispatch({type:'knowledge',id:c.id,articleId:a.id});setModal('source');};
 const changeTab=(t:string)=>{setTab(t);if(t==='Knowledge')caseService.dispatch({type:'knowledge',id:c.id,articleId:articleFor(c).id});};
 const i=currentInteraction(c),p=playerFor(c),r=routingFor(c),rg=isResponsible(c);
 const cases=Object.values(state.cases);const filtered=cases.filter(x=>[x.id,playerFor(x).name,x.title].join(' ').toLowerCase().includes(search.toLowerCase())&&Object.entries(filters).every(([k,v])=>!v||x[k as keyof typeof filters]===v));
 const caseCount=cases.filter(x=>x.status!=='Resolvido').length;
 return <div className={`bmg ${embedded?'embedded':''}`} data-host={host}>
 {!embedded&&<aside className="sidebar"><div className="wordmark"><span className="brand-symbol">M</span><span>BET<span className="gold">MGM</span><small>PLAYER CARE</small></span></div><Label>Workspace</Label><nav aria-label="Navegação principal">{(['Inbox','Cases','Players','Knowledge','Supervisor'] as View[]).map(v=><button key={v} onClick={()=>navigate(v)} className={view===v?'active':''}><Icon name={v}/><span>{v}</span>{v==='Cases'&&<small>{caseCount}</small>}</button>)}</nav><div className="sidebar-bottom"><div className="connected"><span/>Operação Brasil</div><small>Experiência de customer care</small><div className="powered">TWILIO FLEX <span>•</span> DEMO LOCAL</div></div></aside>}
 <div className="workspace-main">{!embedded&&<header className="topbar"><div><span className="breadcrumb">BetMGM Player Care <span>/</span></span><strong>{view}</strong></div><div className="row"><button className="text-button" onClick={()=>setModal('architecture')}><Icon name="architecture" size={17}/>Arquitetura</button><button className="mode-button" onClick={()=>setModal('demo')}><span/>Modo Demo</button><button className="icon-button" title="Reiniciar Demo" aria-label="Reiniciar Demo" onClick={()=>setModal('reset')}><Icon name="reset"/></button><div className="agent-avatar" title="Agente demonstrativo">{c.owner.split(' ').map(n=>n[0]).join('')}</div></div></header>}
 <main>
 {embedded&&<div className="flex-page-tools" aria-label="Ferramentas da demonstração"><span className="eyebrow">{view}</span><div className="row"><button className="text-button" onClick={()=>setModal('architecture')}><Icon name="architecture" size={16}/>Arquitetura</button><button className="mode-button" onClick={()=>setModal('demo')}><span/>Modo Demo</button><button className="icon-button" title="Reiniciar Demo" aria-label="Reiniciar Demo" onClick={()=>setModal('reset')}><Icon name="reset" size={17}/></button></div></div>}
 <div className="page-title"><div><Label>OPERAÇÃO BRASIL / PLAYER CARE</Label><h1>{view==='Inbox'?'Cada conversa, com contexto.':view==='Cases'?'O trabalho continua.':view==='Players'?'Uma história, todos os contatos.':view==='Knowledge'?'Conhecimento que participa.':'A operação, em perspectiva.'}</h1><p>{view==='Inbox'?'Conversa, Case e inteligência no mesmo lugar.':view==='Cases'?'Cases persistem além dos canais e das interações.':view==='Players'?'Contexto seguro para cuidar de cada jogador.':view==='Knowledge'?'Orientação aprovada, acessível durante o atendimento.':'Filas e sinais para decisões de atendimento.'}</p></div>{view==='Inbox'?<button className="secondary" disabled={rg||!i.ended||c.status==='Resolvido'} onClick={()=>setModal('email')}><Icon name="mail"/>Simular novo contato</button>:<Badge>Brasil · Português</Badge>}</div>
 {state.notice&&<div role="status" className="notice"><Icon name="check" size={17}/>{state.notice}</div>}
 {view==='Inbox'&&<div className="inbox-layout"><aside className="work-queue"><div className="queue-heading"><h2>Meu trabalho</h2><Badge>{cases.filter(x=>!currentInteraction(x).ended).length}</Badge></div><p className="muted queue-caption">Contextualizado e priorizado</p>{cases.map(x=><button key={x.id} className={`task-card ${x.id===c.id?'selected':''}`} onClick={()=>select(x.id)}><div className="row spread"><Avatar c={x} small/><span className="task-channel"><Icon name={currentInteraction(x).channel==='Email'?'mail':'chat'} size={14}/>{currentInteraction(x).channel}</span></div><strong>{playerFor(x).name}</strong><p>{x.title}</p><div className="row spread"><Badge tone={isResponsible(x)?'green':'amber'}>{x.priority}</Badge><span className="muted">{currentInteraction(x).ended?'Encerrada':`${x.sla} min`}</span></div><footer>{x.id}<span>{x.owner.split(' ')[0]}</span></footer></button>)}<div className="queue-foot"><Icon name="shield"/><p>O significado da conversa define o encaminhamento.</p></div></aside>
 <section className="conversation"><header className="conversation-header"><div className="row"><Avatar c={c} small/><div><h2>{p.name}</h2><p>{i.channel} #{i.id} <span>·</span> {i.ended?'Encerrada':'Em atendimento'}</p></div></div><button className="text-button" onClick={()=>{setCaseOpen(true);navigate('Cases');}}>{c.id}<Icon name="arrow" size={14}/></button></header><div className={`routing ${rg?'rg':''}`}><div className="row"><Icon name={rg?'shield':'spark'} size={18}/><strong>{c.queue}</strong><Badge tone={rg?'green':'amber'}>{c.priority}</Badge></div><p>Roteado por: {r.explanation}</p><p className="routing-sentiment">{r.intent} <span>·</span> {r.sentiment}</p><details><summary>Entender encaminhamento</summary><dl className="facts"><div><dt>Intenção</dt><dd>{r.intent}</dd></div><div><dt>Contexto</dt><dd>{r.secondary}</dd></div><div><dt>Sentimento</dt><dd>{r.sentiment}</dd></div><div><dt>Política</dt><dd>{r.policy}</dd></div></dl></details></div>
 <div className="message-area"><div className="date-divider">HOJE · {i.messages[0].time}</div>{i.channel==='Email'&&<><div className="continuity"><Icon name="check"/><div><strong>Case aberto encontrado · {c.id}</strong><p>Histórico do Web Chat, {c.notes.length} nota(s) e {c.knowledge.length} fonte(s) recuperados.</p><details><summary>Resumo anterior</summary><p>{i.summary}</p></details></div></div><div className="email-meta"><h3>Acompanhamento da validação PIX</h3><p><b>De:</b> {p.email}<br/><b>Para:</b> playercare@example.test</p><span className="attachment">Anexo ilustrativo · referencia.txt · 1 KB</span></div></>}
 {i.messages.map((m,n)=><div className={`message ${m.author}`} key={`${i.id}-${n}`}><span>{m.author==='player'?p.name:m.agentName||c.owner} <small>{m.time}</small></span><div>{m.body.split('\n').map((line,j)=><p key={j}>{line}</p>)}</div></div>)}
 <div className="system-event"><span/>Case {c.id} vinculado à interação</div>{c.owner==='Rafael Lima'&&<div className="continuity"><Icon name="check"/><div><strong>Contexto transferido</strong><p>Mesmo Case, mesma história. {c.owner} recebeu o contexto.</p><details><summary>Resumo recebido</summary><p>{c.handoffSummary}</p></details></div></div>}{i.ended&&<div className="ended"><Icon name="check"/><h3>Interação encerrada</h3><p>{c.status==='Resolvido'?'Case resolvido. O histórico continua disponível.':`O Case ${c.id} continua ${c.status.toLowerCase()}.`}</p><button className="secondary" onClick={()=>{setCaseOpen(true);navigate('Cases');}}>Abrir Case</button></div>}</div>
 {!i.ended&&<div className="composer"><div className="row spread"><Label>{i.channel==='Email'?'Resposta por Email':'Resposta ao jogador'}</Label><button className="text-button" onClick={()=>changeTab('Assist')}><Icon name="spark" size={15}/>Assist</button></div><textarea aria-label="Resposta ao jogador" placeholder="Escreva uma resposta ou use uma sugestão do Assist…" value={state.drafts[c.id]} onChange={e=>caseService.dispatch({type:'draft',id:c.id,text:e.target.value})}/><div className="row spread"><button className="text-button subdued" onClick={()=>caseService.dispatch({type:'end',id:c.id})}>Encerrar interação</button><button className="primary" disabled={!state.drafts[c.id].trim()} onClick={()=>caseService.dispatch({type:'send',id:c.id})}>Enviar resposta <Icon name="arrow" size={16}/></button></div></div>}
 <footer className="conversation-footer"><Icon name="shield" size={13}/>Ambiente demonstrativo · nenhuma mensagem externa é enviada</footer></section>
 <aside className="context-panel"><div className="context-tabs" role="tablist" aria-label="Contexto do atendimento">{['Player','Case','Assist','Knowledge'].map(t=><button role="tab" aria-selected={tab===t} key={t} className={tab===t?'active':''} onClick={()=>changeTab(t)}>{t}</button>)}</div><div className="panel-body" role="tabpanel" aria-label={tab} key={c.id+tab}>{tab==='Player'&&<PlayerPanel c={c} onCase={()=>changeTab('Case')}/>} {tab==='Case'&&<CasePanel c={c} onHandoff={()=>setModal('handoff')}/>} {tab==='Assist'&&<AssistPanel c={c} onSource={openSource} onKnowledge={()=>changeTab('Knowledge')}/>} {tab==='Knowledge'&&<><div className="row spread"><Label>Relevante para esta conversa</Label><Icon name="Knowledge"/></div><KnowledgeCard article={articleFor(c)} onSource={()=>openSource(articleFor(c))} onUse={()=>{caseService.dispatch({type:'draft',id:c.id,text:articleFor(c).response});}}/><button className="text-button" onClick={()=>navigate('Knowledge')}><Icon name="search" size={16}/>Pesquisar conhecimento</button></>}</div></aside></div>}
 {view==='Cases'&&<><div className="module-toolbar"><Search value={search} onChange={setSearch} placeholder="Buscar Case, jogador ou assunto"/>{(['status','priority','queue','owner'] as const).map(k=><select key={k} aria-label={`Filtrar ${k}`} value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}><option value="">{({status:'Todos os status',priority:'Prioridade',queue:'Todas as filas',owner:'Responsável'})[k]}</option>{Array.from(new Set(cases.map(x=>x[k]))).map(v=><option key={v}>{v}</option>)}</select>)}</div><div className={`cases-layout ${caseOpen?'with-detail':''}`}><section className="case-table"><div className="table-header"><span>CASE / JOGADOR</span><span>STATUS / PRIORIDADE</span><span>FILA / RESPONSÁVEL</span></div>{filtered.map(x=><button className={`case-row ${caseOpen&&x.id===c.id?'selected':''}`} key={x.id} onClick={()=>{select(x.id);setCaseOpen(true);}}><span><b>{x.id}</b><strong>{playerFor(x).name}</strong><small>{x.title}</small></span><span><Badge tone={x.status==='Resolvido'?'green':'amber'}>{x.status}</Badge><small>{x.priority} · SLA {x.sla} min</small></span><span>{x.queue}<small>{x.owner}</small><small>{x.interactions.length} interação(ões)</small></span></button>)}{!filtered.length&&<p className="empty">Nenhum Case corresponde aos filtros.</p>}<footer className="table-foot">{filtered.length} Cases · trabalho persistente, independente do chat</footer></section>{caseOpen&&<aside className="case-detail"><div className="row spread"><Label>Detalhes do Case</Label><button className="icon-button" aria-label="Fechar detalhes" onClick={()=>setCaseOpen(false)}><Icon name="close"/></button></div><CasePanel c={c} full onHandoff={()=>setModal('handoff')}/></aside>}</div></>}
 {view==='Players'&&<><div className="module-toolbar"><Search value={search} onChange={setSearch} placeholder="Buscar nome, Player ID, email ou telefone"/></div><div className="players-layout"><section className="player-list">{players.filter(x=>[x.name,x.id,x.email,x.phone].join(' ').toLowerCase().includes(search.toLowerCase())).map(x=>{const pc=cases.find(y=>y.playerId===x.id)!;return <button key={x.id} className={`player-row ${c.playerId===x.id?'selected':''}`} onClick={()=>select(pc.id)}><Avatar c={pc}/><span><strong>{x.name}</strong><small>{x.id}</small><small>{x.email}</small></span><Icon name="arrow"/></button>;})}{!players.some(x=>[x.name,x.id,x.email,x.phone].join(' ').toLowerCase().includes(search.toLowerCase()))&&<p className="empty">Nenhum jogador encontrado.</p>}</section><section className="player-detail"><div><PlayerPanel c={c} onCase={()=>{setCaseOpen(true);navigate('Cases');}}/></div><div><Label>Histórico de interações</Label>{c.interactions.map(x=><div className="history-card" key={x.id}><Badge>{x.channel}</Badge><h3>#{x.id} · {x.ended?'Encerrada':'Em atendimento'}</h3><p>{x.summary}</p><small>Case {c.id}</small></div>)}<Label>Contato demonstrativo</Label><p>{p.email}<br/>{p.phone}</p></div></section></div></>}
 {view==='Knowledge'&&<><div className="module-toolbar"><Search value={search} onChange={setSearch} placeholder="Pesquisar conhecimento"/><select aria-label="Categoria do conhecimento" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas as categorias</option>{Array.from(new Set(articles.map(a=>a.category))).map(cat=><option key={cat}>{cat}</option>)}</select><Badge tone="green">Conteúdo aprovado · Demo</Badge></div><div className="row spread section-heading"><Label>Atualizados recentemente</Label><span className="muted">Biblioteca local · 5 artigos</span></div><div className="knowledge-grid">{articles.filter(a=>(!category||a.category===category)&&[a.title,a.category,a.source].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.updated.localeCompare(a.updated)).map(a=><KnowledgeCard key={a.id} article={a} onSource={()=>openSource(a)}/>)}{!articles.some(a=>(!category||a.category===category)&&[a.title,a.category,a.source].join(' ').toLowerCase().includes(search.toLowerCase()))&&<p className="empty">Nenhum artigo encontrado.</p>}</div></>}
 {view==='Supervisor'&&<><div className="supervisor-stats"><div><Label>Em espera</Label><strong>12</strong><p>4 filas de atendimento</p></div><div><Label>Nível de serviço</Label><strong>94<span>%</span></strong><p>Últimas 2 horas</p></div><div><Label>Agentes disponíveis</Label><strong>18</strong><p>Operação Brasil</p></div><div className="quiet-stat"><Icon name="shield" size={26}/><p>Atendimento especializado<br/><strong>Jogo Responsável</strong></p><Badge tone="green">Estável</Badge></div></div><div className="supervisor-layout"><section className="operations"><h2>Visão das filas</h2><table><thead><tr><th>Fila</th><th>Espera</th><th>Maior espera</th><th>Nível de serviço</th><th>Disponíveis</th></tr></thead><tbody>{[['Payments & Verification','7','04:12','91%','6'],['Responsible Gaming','1','00:28','100%','3'],['Technical Support','3','02:06','94%','5'],['General Support','1','00:43','98%','4']].map(row=><tr key={row[0]}>{row.map((cell,n)=><td key={n}>{cell}</td>)}</tr>)}</tbody></table><p className="muted">Recorte operacional demonstrativo · 10:42</p></section><section className="signals"><div className="row"><Icon name="spark"/><h2>Conversation signals</h2></div>{['Contatos sobre verificação de PIX +38% nas últimas 2h','Contatos sobre acesso à conta aumentando','Jogo Responsável estável'].map((s,n)=><button className="signal" key={s} onClick={()=>{setSignal(n);setModal('signal');}}><Label>{n===0?'ATENÇÃO OPERACIONAL':n===1?'ACOMPANHAR':'POLÍTICA'}</Label><h3>{s}</h3><span>Investigar sinal <Icon name="arrow" size={15}/></span></button>)}</section></div></>}
 </main><footer className="workspace-footer"><span>BETMGM PLAYER CARE</span><span>Conversa + Case + Contexto</span><span>{embedded?'Plugin local em Twilio Flex':'Standalone offline'} · Dados sintéticos</span></footer></div>
 {modal==='architecture'&&<Modal title="Arquitetura da experiência" onClose={()=>setModal(null)}><Architecture/></Modal>}
 {modal==='demo'&&<Modal title="Modo Demo · guia do apresentador" onClose={()=>setModal(null)}><p className="lead-small">Tudo que acontece neste workspace é local e sintético.</p><div className="demo-map"><section><Label>Native Twilio</Label><p>Flex UI, Plugins, TaskRouter, canais, Flex Email e operações de supervisão. Conversation Orchestrator, Memory, Enterprise Knowledge e Intelligence compõem a arquitetura alvo.</p></section><section><Label>Custom / BetMGM</Label><p>Case Center, Player 360, Case Service, ações e tema. Cases não são objetos nativos do Flex.</p></section><section><Label>Demonstrativo</Label><p>Jogadores, pagamentos, KYC, conversas, roteamento, Cases, políticas, métricas e Assist determinístico. Sem AI externa ou envio real.</p></section><section><Label>Integração de produção</Label><p>APIs BetMGM e persistência própria. Dados sensíveis nos sistemas de registro; somente contexto mínimo chega ao agente.</p></section></div><details><summary>Atributos de roteamento · {c.id}</summary><pre>{JSON.stringify({...r.attributes,channel:i.channel==='Email'?'email':'web'},null,2)}</pre></details><p className="boundary">Paleta temporária inspirada na marca. Políticas fictícias, sem validade operacional. Reiniciar restaura todos os estados da demo.</p></Modal>}
 {modal==='source'&&<Modal title="Fonte de conhecimento" onClose={()=>setModal(null)}><Label>{source.id} · {source.source}</Label><h2>{source.title}</h2><Badge tone="green">Aprovado no cenário demonstrativo</Badge><ol className="source-guidance">{source.guidance.map(g=><li key={g}>{g}</li>)}</ol><h3>Versão e histórico</h3><p>v{source.version} · {source.updated} · Revisão editorial demonstrativa</p><p className="boundary">Fonte local sintética. Em produção, o conteúdo precisa de aprovação e governança BetMGM e pode ser disponibilizado por Enterprise Knowledge.</p></Modal>}
 {modal==='handoff'&&<Modal title="Resumo para handoff" onClose={()=>setModal(null)}><div className="handoff-player"><Avatar c={c}/><div><h3>{p.name}</h3><p>{c.id} · {c.title}</p></div></div><blockquote>{handoffFor(c)}</blockquote><div className="handoff-route"><div><Label>De</Label><p>{c.queue}<br/>{c.owner}</p></div><Icon name="arrow"/><div><Label>Para</Label><p>{rg?'Responsible Gaming':'Verification'}<br/>Rafael Lima</p></div></div><div className="preserved"><Icon name="check"/><span>Conversa · Case · {c.notes.length} nota(s) · SLA {c.sla} min · Player · {c.knowledge.length} fonte(s) · Histórico</span></div><button className="primary" onClick={()=>{caseService.dispatch({type:'transfer',id:c.id});setModal(null);setTab('Case');}}>{rg?'Confirmar encaminhamento':'Transferir para Verification'}</button><p className="muted">Transferência demonstrativa. Nenhuma alteração no TaskRouter.</p></Modal>}
 {modal==='email'&&<Modal title="Simular novo contato" onClose={()=>setModal(null)}><Label>Continuidade multicanal</Label><h2>O canal muda. A história continua.</h2><label className="field-label">Canal<select aria-label="Canal do novo contato"><option>Email</option></select></label><p>{p.name} retorna para acompanhar o Case <strong>{c.id}</strong>.</p><div className="memory"><p>O histórico anterior, as notas e o conhecimento consultado acompanham o novo atendimento.</p></div><button className="primary" onClick={()=>{caseService.dispatch({type:'email',id:c.id});setModal(null);setTab('Case');}}>Criar interação Email simulada <Icon name="arrow" size={16}/></button></Modal>}
 {modal==='reset'&&<Modal title="Reiniciar Demo" onClose={()=>setModal(null)}><p>Restaurar Lucas e Ana, Cases, interações, notas, filas, responsáveis, SLA, conhecimento e Assist ao início da apresentação?</p><button className="primary" onClick={()=>{caseService.dispatch({type:'reset'});setModal(null);setTab('Player');setCaseOpen(false);setFilters({status:'',queue:'',priority:'',owner:''});setCategory('');navigate('Inbox');}}>Reiniciar agora</button></Modal>}
 {modal==='signal'&&<Modal title="Investigar sinal operacional" onClose={()=>setModal(null)}><Label>Conversation Intelligence · sinal demonstrativo</Label><h2>{['Verificação de PIX · +38%','Acesso à conta · em crescimento','Jogo Responsável · estável'][signal]}</h2><p>Recorte sintético das últimas 2 horas. Não representa dados reais da operação.</p><h3>Cases relacionados</h3>{signal===1?<p>Nenhum Case individual incluído neste recorte anonimizado.</p>:<button className="case-link" onClick={()=>{select(signal===2?'BET-18491':'BET-18472');setCaseOpen(true);setModal(null);navigate('Cases');}}>{signal===2?'BET-18491':'BET-18472'}<Icon name="arrow"/></button>}<h3>Exemplo anonimizado</h3><blockquote>{['“O pagamento não apareceu e a conta pede verificação.”','“Não consigo acessar minha conta.”','“Preciso de ajuda para interromper minha participação.”'][signal]}</blockquote><h3>Investigação operacional sugerida</h3><p>{['Verificar a latência dos eventos PIX e a etapa de validação de novas contas. Comparar os sinais com a telemetria dos sistemas de origem antes de concluir uma causa.','Revisar incidentes de autenticação e o fluxo de recuperação com a equipe técnica. Não solicitar senhas aos jogadores.','Acompanhar capacidade da fila especializada e aderência ao procedimento de proteção.'][signal]}</p></Modal>}
 </div>;
}
function Search({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="search"><Icon name="search" size={18}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>;}
