import { describe,it,expect,vi } from 'vitest';
import request from 'supertest';
import { createApp } from './app';
import { defaults } from '../src/demo';
describe('Boti backend boundary',()=>{
 it('works offline and exposes no configuration values',async()=>{const app=createApp();const res=await request(app).post('/api/boti/analyze').send({scenario:'customer'});expect(res.status).toBe(200);expect(res.body).toEqual(defaults.customer);expect((await request(app).get('/api/boti/channel')).body.externalSendingEnabled).toBe(false);});
 it('rejects invalid scenarios and external browser origins',async()=>{expect((await request(createApp()).post('/api/boti/analyze').send({scenario:'invalid'})).status).toBe(400);expect((await request(createApp()).post('/api/boti/analyze').set('Origin','https://example.com').send({scenario:'customer'})).status).toBe(403);});
 it('falls back for failed provider calls without leaking errors',async()=>{const fetcher=vi.fn().mockRejectedValue(new Error('sensitive-provider-detail'));const res=await request(createApp({apiKey:'test-only',model:'configured-model',fetcher})).post('/api/boti/analyze').send({scenario:'franchise'});expect(res.body).toEqual(defaults.franchise);expect(res.text).not.toContain('sensitive-provider-detail');});
 it('validates successful structured output and keeps credentials server-side',async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(defaults.customer)}]}]})));const res=await request(createApp({apiKey:'test-only',model:'configured-model',fetcher})).post('/api/boti/analyze').send({scenario:'customer'});expect(res.body).toEqual(defaults.customer);const sent=JSON.parse(fetcher.mock.calls[0][1].body);expect(sent.store).toBe(false);expect(sent.model).toBe('configured-model');expect(sent.text.format.strict).toBe(true);expect(res.text).not.toContain('test-only');});
 it('falls back for incomplete and malformed model output',async()=>{for(const output of [{status:'incomplete'},{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'{"summary":42}'}]}]}]){const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify(output)));const res=await request(createApp({apiKey:'test-only',model:'configured-model',fetcher})).post('/api/boti/analyze').send({scenario:'customer'});expect(res.body).toEqual(defaults.customer);}});
 it('blocks oversized request bodies',async()=>{const res=await request(createApp()).post('/api/boti/analyze').send({scenario:'customer',extra:'x'.repeat(25000)});expect(res.status).toBe(400);});
});
