import {describe,it,expect,vi} from 'vitest';
import request from 'supertest';
import {createHmac} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {createApp} from './app';
import {activityConfig,parseInput} from './contract';
import {mapInput,defaults} from '../shared/model';
const payload=mapInput(defaults);const secret='test-secret-never-public';
const env={TWILIO_ACCOUNT_SID:`AC${'a'.repeat(32)}`,TWILIO_AUTH_TOKEN:secret,ACHE_JOURNEY_WHATSAPP_FROM:defaults.sender,ACHE_JOURNEY_CONTENT_SID:defaults.contentSid,ACHE_JOURNEY_LIVE_ENABLED:'true'};
function sign(body:unknown,exp=Date.now()/1000+60){const header=Buffer.from(JSON.stringify({alg:'HS256'})).toString('base64url');const p=Buffer.from(JSON.stringify({...body as object,exp})).toString('base64url');return `${header}.${p}.${createHmac('sha256',secret).update(`${header}.${p}`).digest('base64url')}`;}
describe('activity contracts and execution',()=>{
 it('follows documented config nesting, bounds and signed lifecycle',()=>{const c=activityConfig('https://example.org','installed-key');expect(c.workflowApiVersion).toBe('1.1');expect(c.type).toBe('Rest');expect(c.arguments.execute).toMatchObject({useJwt:true,retryCount:0,timeout:20000,concurrentRequests:1});expect(c.configurationArguments.applicationExtensionKey).toBe('installed-key');expect(c.userInterfaces.configModal.url).toBe('https://example.org/activity/index.html');expect(c.schema.arguments.execute.outArguments).toHaveLength(2);});
 it('offline execution never calls provider or invents delivery/SID',async()=>{const provider=vi.fn();const response=await request(createApp(env,provider)).post('/api/simulate').send(payload);expect(response.status).toBe(200);expect(response.body).toMatchObject({executionMode:'simulation',providerStatus:'not_called'});expect(response.body.sid).toBeUndefined();expect(provider).not.toHaveBeenCalled();});
 it('merges inArguments but rejects duplicate keys, unresolved bindings and unrelated channels',()=>{expect(parseInput({inArguments:Object.entries(payload.inArguments[0]).map(([k,v])=>({[k]:v}))})).toEqual(payload.inArguments[0]);expect(()=>parseInput({inArguments:[payload.inArguments[0],{phone:'+5500000000000'}]})).toThrow();expect(()=>parseInput({inArguments:[{...payload.inArguments[0],phone:'{{Contact.Phone}}'}]})).toThrow();expect(()=>parseInput({inArguments:[{...payload.inArguments[0],channel:'rcs'}]})).toThrow();});
 it('returns input errors without leaking input',async()=>{const r=await request(createApp()).post('/api/simulate').send({inArguments:[{phone:secret}]});expect(r.status).toBe(400);expect(JSON.stringify(r.body)).not.toContain(secret);});
 it('supports deterministic provider failure and continue policy',async()=>{const app=createApp();expect((await request(app).post('/api/simulate').send({...payload,scenario:'provider-failure'})).status).toBe(502);const r=await request(app).post('/api/simulate').send({inArguments:[{...payload.inArguments[0],errorBehavior:'continue'}],scenario:'provider-failure'});expect(r.status).toBe(200);expect(r.body.continued).toBe(true);expect(r.body.providerStatus).toBe('not_called');});
 it('requires signed unexpired JWT on execute and lifecycle',async()=>{const app=createApp({ACHE_JOURNEY_JWT_SECRET:secret});expect((await request(app).post('/api/activity/execute').send(payload)).status).toBe(401);expect((await request(app).post('/api/activity/execute').type('text/plain').send(sign(payload,1))).status).toBe(401);expect((await request(app).post('/api/activity/execute').type('text/plain').send(sign(payload))).status).toBe(200);expect((await request(app).post('/api/activity/validate').type('text/plain').send(sign({arguments:{execute:payload}}))).body.valid).toBe(true);expect((await request(app).post('/api/activity/validate').type('text/plain').send(sign({}))).status).toBe(400);});
 it('does not expose credentials in public responses/assets',async()=>{const app=createApp(env);for(const path of ['/api/readiness','/activity/config.json'])expect((await request(app).get(path)).text).not.toContain(secret);for(const path of ['src/App.tsx','public/activity/customActivity.js'])expect(readFileSync(new URL(`../${path}`,import.meta.url),'utf8')).not.toMatch(/TWILIO_AUTH_TOKEN|TWILIO_API_KEY_SECRET/);});
 it('blocks live by default, without confirmation, with wrong sender or cross origin',async()=>{const provider=vi.fn();expect((await request(createApp()).post('/api/live').send(payload)).status).toBe(403);const app=createApp(env,provider);expect((await request(app).post('/api/live').send(payload)).status).toBe(400);expect((await request(app).post('/api/live').set('Origin','https://evil.example').send(payload)).status).toBe(403);expect(provider).not.toHaveBeenCalled();});
 it('returns actual provider SID/status, deduplicates, sanitizes provider errors',async()=>{const provider=vi.fn().mockResolvedValue({sid:`SM${'a'.repeat(32)}`,status:'queued'});const app=createApp(env,provider);const body={...payload,confirmation:'CONFIRMO ENVIO WHATSAPP',optIn:true,requestId:'test-request-123'};const r=await request(app).post('/api/live').send(body);expect(r.body).toEqual({executionMode:'real',sid:`SM${'a'.repeat(32)}`,status:'queued'});await request(app).post('/api/live').send(body);expect(provider).toHaveBeenCalledTimes(1);const fail=await request(createApp(env,vi.fn().mockRejectedValue(new Error(secret)))).post('/api/live').send(body);expect(fail.status).toBe(502);expect(fail.text).not.toContain(secret);expect(fail.body.sid).toBeUndefined();});
});
