// Optional browser regression harness; uses an existing Playwright installation.
// PLAYWRIGHT_MODULE=/absolute/path/to/playwright/index.mjs node apps/vr/scripts/browser-smoke.mjs
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, permissions: ['clipboard-read', 'clipboard-write'] });
const page = await ctx.newPage();
const errors = [], external = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(`${m.text()} (${m.location().url})`); });
await ctx.route('**/*', route => {
  const url = new URL(route.request().url());
  if (url.hostname !== '127.0.0.1' && url.protocol !== 'data:') { external.push(url.href); return route.abort(); }
  return route.continue();
});
const click = name => page.getByRole('button', { name, exact: true }).click();
const has = async text => assert.ok(await page.getByText(text, { exact: false }).first().isVisible(), text);
const screenshot = name => page.screenshot({ path: `/tmp/vr-${name}.png`, fullPage: true });
try {
  await page.goto(process.env.VR_URL || 'http://127.0.0.1:5177');
  await has('VR Sales Journey');
  await has('Twilio Orchestration');
  await has('O que acontece por trás da conversa');
  assert.equal(await page.locator('.stack-product.pending').count(), 6);
  assert.equal(await page.locator('.stack-product.active').count(), 0);
  assert.equal(await page.locator('.stack-products').getByText('Salesforce').count(), 0);
  assert.equal(await page.getByRole('region', { name: 'VR / PARTNERS' }).getByText('Salesforce').count(), 1);
  await screenshot('start');
  await click('Iniciar demo');
  await page.getByRole('checkbox').uncheck();
  assert.ok(await page.getByRole('button', { name: 'Continuar no WhatsApp', exact: true }).isDisabled());
  assert.ok(await page.getByRole('button', { name: 'Próxima etapa', exact: true }).isDisabled());
  await page.getByRole('checkbox').check();
  await screenshot('landing');
  await click('Continuar no WhatsApp');
  await has('Formulário enviado → primeira conversa:');
  await screenshot('first-contact');
  await has('WhatsApp Business API · Conversa iniciada');
  await has('Conecta o agente de IA à conversa');
  assert.equal(await page.locator('[data-product="agent"]').getAttribute('class'), 'stack-product active');
  await page.locator('.context summary').click();
  assert.equal(await page.locator('.context .fields > div').count(), 4);
  await page.locator('.context summary').click();
  await click('Vamos conversar');
  await click('Sim, mas estamos avaliando trocar de fornecedor.');
  await click('Queremos melhorar a experiência e simplificar a gestão.');
  await click('Sim.');
  await has('RESUMO DO LEAD');
  await has('Mantém o contexto do cliente ao longo da jornada');
  await page.locator('.context summary').click();
  assert.equal(await page.locator('.context .fields > div').count(), 8);
  assert.equal(await page.locator('.context .field-new').count(), 2);
  await page.locator('.context summary').click();
  await click('Ver CRM simulado');
  await has('Resumo da conversa anexado');
  await screenshot('crm');
  await has('Coordena ações e ferramentas');
  assert.ok(await page.getByRole('region', { name: 'VR / PARTNERS' }).getByText('Oportunidade criada · simulação', { exact: true }).isVisible());
  await click('Continuar com proposta');
  await click('Tenho uma dúvida');
  await has('O que acontece agora?');
  await click('Voltar à conversa');
  await click('Ver proposta');
  await click('Abrir documento');
  assert.ok(await page.getByRole('dialog').isVisible());
  await page.keyboard.press('Escape');
  assert.ok(!await page.getByRole('dialog').isVisible());
  await click('Abrir documento');
  await click('Fechar documento');
  await click('Abrir documento');
  await click('Continuar para verificação');
  await click('Enviar código de verificação');
  assert.equal(await page.locator('[data-product="verify"]').getAttribute('class'), 'stack-product active');
  await page.getByLabel('Código de verificação demonstrativo').fill('000000');
  await click('Confirmar');
  await has('Use 123456');
  await page.getByLabel('Código de verificação demonstrativo').fill('123456');
  await click('Confirmar');
  await has('Identidade verificada');
  assert.equal(await page.locator('[data-product="verify"]').getAttribute('class'), 'stack-product completed');
  await click('Continuar para o aceite');
  await has('Aceite concluído — simulação');
  await click('Ver boleto');
  await has('R$ 12.480,00');
  await click('Ver boleto');
  await has('SEM VALOR · NÃO PAGÁVEL');
  await page.getByRole('dialog').getByRole('button', { name: 'Copiar código' }).click();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), 'DEMO-ACME-12480-NOT-PAYABLE');
  await click('Fechar documento');
  await click('Copiar código');
  await has('Copiado — código demonstrativo, não pagável');
  await screenshot('payment');
  await has('Lembrete de pagamento preparado');
  assert.equal(await page.locator('[data-product="intelligence"]').getAttribute('class'), 'stack-product pending');
  await click('Falar com alguém');
  await has('Cliente solicitou atendimento humano');
  assert.deepEqual(await page.locator('.handoff-chain strong').allTextContents(), ['Conversation Orchestrator', 'Conversation Memory', 'EPS Partner A']);
  assert.deepEqual(await page.locator('.scene-detail .fields dd').allTextContents(), await page.locator('.context .fields dd').allTextContents());
  assert.ok(!await page.getByRole('log').getByText('Olá, Lucas. Passando', { exact: false }).count());
  await click('Conectar especialista da EPS');
  await has('HUMANO — EPS Partner A');
  await has('Métricas demonstrativas — não são resultados de clientes');
  await screenshot('handoff');
  await has('Conversa pronta para análise · SIMULAÇÃO');
  await has('Nenhuma análise foi executada nesta demo.');
  assert.equal(await page.locator('[data-product="intelligence"]').getAttribute('class'), 'stack-product active');
  await click('Pagamento');
  await page.locator('.twilio-events summary').click();
  assert.equal(await page.locator('.twilio-events li').count(), 6);
  await page.locator('.twilio-events summary').click();
  await page.locator('.business-progress summary').click();
  assert.equal(await page.locator('.business-progress li.completed').count(), 10);
  await page.locator('.business-progress summary').click();
  await click('Simular lembrete');
  await has('Lembrete enviado · SIMULAÇÃO');
  await click('Ver boleto');
  await click('Fechar documento');
  await click('Preciso de ajuda');
  await click('Conectar especialista da EPS');
  for (const [name, expected] of [['Primeiro contato', 'O interesse ainda está aqui.'], ['Qualificação', '1 de 3 perguntas'], ['CRM', 'Resumo da conversa anexado'], ['Pagamento', 'R$ 12.480,00'], ['Transferência', 'CONTEXTO DO CLIENTE']]) {
    await click(name); await has(expected);
    await click('Etapa anterior'); await click('Próxima etapa'); await has(expected);
    await click('Reiniciar demo'); await has('Iniciar demo');
    assert.equal(await page.locator('.stack-product.pending').count(), 6);
  }
  await click('Próxima etapa');
  await page.getByRole('checkbox').uncheck();
  await click('Reiniciar demo'); await click('Iniciar demo');
  assert.ok(await page.getByRole('checkbox').isChecked());
  await click('Transferência');
  await page.reload(); await has('Iniciar demo');
  await page.evaluate(() => document.fonts.ready);
  await page.waitForLoadState('networkidle');
  await ctx.setOffline(true);
  await click('Iniciar demo');
  for (let i = 1; i < 17; i++) await click('Próxima etapa');
  await has('Context preserved');
  await click('Reiniciar demo'); await has('Iniciar demo');
    assert.equal(await page.locator('.stack-product.pending').count(), 6);
  await ctx.setOffline(false);
  for (const size of [{ width: 1280, height: 720 }, { width: 390, height: 844 }]) {
    await page.setViewportSize(size); await click('Pagamento');
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'no horizontal overflow');
    if (size.width === 1280) {
      const actions = await page.locator('.chat-actions').boundingBox();
      const controls = await page.locator('.controls').boundingBox();
      assert.ok(actions.y + actions.height <= controls.y, 'presentation controls do not cover customer actions');
    }
    await screenshot(`${size.width}`);
    await click('Reiniciar demo');
  }
  assert.deepEqual(external, [], 'zero external requests');
  assert.deepEqual(errors, [], 'no console or runtime errors');
  console.log('PASS: full VR flow, all actions, 5 jumps, previous/next, reset, consent, wrong OTP, modals, clipboard, early/late handoff, refresh, offline interaction, desktop/mobile, zero external requests/errors.');
} finally { await browser.close(); }
