import { describe,it,expect } from 'vitest';
import { initialState,reducer,handoff } from './demo';
describe('isolated demo journeys',()=>{
 it('offers pickup once, requires acceptance and preserves history',()=>{let s=initialState();expect(reducer(s,{type:'resolve'})).toBe(s);s=reducer(s,{type:'pickup'});expect(s.customer.resolved).toBe(false);expect(s.customer.messages).toHaveLength(2);expect(reducer(s,{type:'pickup'})).toBe(s);s=reducer(s,{type:'resolve'});expect(s.customer.resolved).toBe(true);expect(s.customer.messages[0].text).toContain('presente para amanhã');expect(s.customer.events.at(-1)).toContain('BOT-84219');expect(reducer(s,{type:'resolve'})).toBe(s);});
 it('escalates with context and does not claim diagnostics completed',()=>{let s=initialState();s=reducer(s,{type:'escalate'});expect(s.franchise.incident).toBe(true);expect(s.franchise.escalated).toBe(true);expect(handoff(s.franchise)).toContain('Orientação ainda não enviada');expect(handoff(s.franchise)).toContain('12 transações');expect(handoff(s.franchise)).toContain('15 min');expect(s.customer).toEqual(initialState().customer);expect(reducer(s,{type:'escalate'})).toBe(s);});
 it('retains guidance and agent messages in N2 handoff',()=>{let s=initialState();s=reducer(s,{type:'guidance'});s=reducer(s,{type:'send',scenario:'franchise',text:'PDV 03 identificado.'});s=reducer(s,{type:'incident'});expect(handoff(s.franchise)).toContain('PDV 03 identificado.');expect(handoff(s.franchise)).toContain('resultados aguardando');});
 it('reset restores both cases and operational actions',()=>{let s=initialState();for(const type of ['pickup','resolve','guidance','incident','escalate'] as const)s=reducer(s,{type});s=reducer(s,{type:'signal',id:'pos'});expect(reducer(s,{type:'signal',id:'pos'})).toBe(s);expect(reducer(s,{type:'reset'})).toEqual(initialState());});
 it('ignores empty or resolved-case replies',()=>{let s=initialState();expect(reducer(s,{type:'send',scenario:'customer',text:'  '})).toBe(s);s=reducer(reducer(s,{type:'pickup'}),{type:'resolve'});expect(reducer(s,{type:'send',scenario:'customer',text:'test'})).toBe(s);});
});
